# Generated by Django 5.2.4 on 2025-07-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_units',
            new_name='servings_unit',
        ),
    ]
